"""add_contact_type_to_call_logs

Revision ID: 7ae227b46641
Revises: db9a94a43611
Create Date: 2026-04-05 15:07:16.597955
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae227b46641'
down_revision: Union[str, None] = 'db9a94a43611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('call_logs', sa.Column('contact_type', sa.String(length=20), nullable=False, server_default='call'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_logs', 'contact_type')
    # ### end Alembic commands ###
